version: '3'

networks:
  default:
  db_default:
    external: true

services:
  server:
    image: official5eta/octopusproxy:server
    container_name: octopusproxy-server
    env_file: .env
    networks:
      default:
        aliases:
          - octopusproxy-server
      db_default:
    ports:
      - "8283:8283"
    restart: always